### PR TITLE
 Added Swarm UI and Delta service

### PR DESCRIPTION
**Pull request by cecton**

### CODE REVIEW

**Review by lordblendi — CHANGES_REQUESTED** [review]
- swarm-admin still doesn't have a tag
- the relation between the the repositories and the pipeline-instances still doesn't exist in the db
- the action 'up' errors the admin-swarm
- the 'docker' docker exists
- the frontend port was chosen by Aad. don't change it. 
- every port except the frontend's should be in the docker-compose.override.yml. don't put that file into gitignore

**Comment by lordblendi** [comment]
Here are some screenshots of the errors I got:

screenshot from 2017-05-03 13-21-26
screenshot from 2017-05-03 13-21-50

**Comment by cecton** [comment]
> swarm-admin still doesn't have a tag

It has 2 but I don't have access to bde2020 on Docker HUB. https://github.com/big-data-europe/mu-swarm-admin-service/releases

> the relation between the the repositories and the pipeline-instances still doesn't exist in the db

First of all, this is not related at all to this PR. Second, please read the appropriate ticket: https://trello.com/c/PtiTw7bA/3-swarm-ui-missing-relation-between-pipeline-and-repository

> the action 'up' errors the admin-swarm

It doesn't seem to work too well with VFS as storage driver for Docker, try with overlay. In for docker-compose.override.yml:
```
version: "2"
services:

  docker:
    environment:
      - DOCKER_DRIVER=overlay2
```

> the 'docker' docker exists

Can you please be more explicit? What is a 'docker' docker?

> the frontend port was chosen by Aad. don't change it.

Sure.

> every port except the frontend's should be in the docker-compose.override.yml. don't put that file into gitignore

Do you plan to add the override inside the repository?

**Comment by lordblendi** [comment]
> First of all, this is not related at all to this PR. Second, please read the appropriate ticket: https://trello.com/c/PtiTw7bA/3-swarm-ui-missing-relation-between-pipeline-and-repository

Ok, I replied there.


> It doesn't seem to work too well with VFS as storage driver for Docker, try with overlay. In for docker- compose.override.yml:
> 
> version: "2"
services:
> 
>   docker:
>     environment:
>       - DOCKER_DRIVER=overlay2

Ok, will try that later.

> Can you please be more explicit? What is a 'docker' docker?

https://github.com/big-data-europe/app-swarm-ui/blob/added-swarmui/docker-compose.yml#L65
This 'docker' fails and exists upon start.

> Do you plan to add the override inside the repository?

Yes, it was already in the dev branch, just forgot to rebase it. Done that now.

**Comment by cecton** [comment]
> Yes, it was already in the dev branch, just forgot to rebase it. Done that now.

Ok done.

> https://github.com/big-data-europe/app-swarm-ui/blob/added-swarmui/docker-compose.yml#L65
> This 'docker' fails and exists upon start.

Sorry I cannot reproduce. Try `docker pull docker:dind`.

**Comment by lordblendi** [comment]
Sorry, forgot to attach this for the 'docker': 
screenshot from 2017-05-03 14-38-18

**Comment by cecton** [comment]
@lordblendi I think we have an issue because the delta service is sending update requests to the swarm-admin while swarm-admin is already upping the application. Any idea what could possibly update the requestedState and send a HTTP request to swarm to up the pipeline at the same time?

**Comment by cecton** [comment]
Swarm admin seems to receive everything in double:
```
[pid: 22|app: 0|req: 9/19] 172.25.0.5 () {42 vars in 577 bytes} [Wed May  3 12:48:18 2017] POST /update => generated 0 bytes in 51869 msecs (HTTP/1.1 204) 2 headers in 86 bytes (0 switches on core 0)
Starting 1d364f90-2ffc-11e7-ad34-000000000000_dispatcher_1 ... done
Creating 1d364f90-2ffc-11e7-ad34-000000000000_dispatcher_2 ... done
[pid: 18|app: 0|req: 2/20] 172.25.0.7 () {60 vars in 1439 bytes} [Wed May  3 12:50:27 2017] POST /services/82666ffb-1ba0-41a9-a423-a10ee0f3b47e/scale => generated 17 bytes in 1054 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 1)
```

**Comment by lordblendi** [comment]
> I think we have an issue because the delta service is sending update requests to the swarm-admin while swarm-admin is already upping the application. Any idea what could possibly update the requestedState and send a HTTP request to swarm to up the pipeline at the same time?

That is the frontend as it wasn't adapted yet. So that is causing the issue?

**Comment by lordblendi** [comment]
I mean the frontend writes the state into the db and then still sends a call to the swarm-admin

**Comment by cecton** [comment]
> I mean the frontend writes the state into the db and then still sends a call to the swarm-admin

Yes, that's what I see in the calls. Actually that's the only place. The scaling works normally.

**Comment by lordblendi** [comment]
I tried the docker driver, result:
```
docker_1       | time="2017-05-04T10:57:56.956455147Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found" 
docker_1       | time="2017-05-04T10:57:56.956713142Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]" 
docker_1       | time="2017-05-04T10:57:56.958188808Z" level=info msg="libcontainerd: new containerd process, pid: 21" 
docker_1       | time="2017-05-04T10:57:57.969482139Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded." 
docker_1       | Error starting daemon: error initializing graphdriver: driver not supported
```

**Review by lordblendi — APPROVED** [review]
We tested them together, they work.

**Pull request merged**
